POST https://ivoplaninic.net:8881/api/login
Content-Type: application/json

{ "email": "planinic.ivki@gmail.com", "password": "Ivimir11" }

###


POST http://localhost:8881/api/loginPOST http://localhost:8881/api/login
Content-Type: application/json

{ "username": "ivo", "password": "Ivimir11" }

###


POST http://localhost:8881/api/login
Content-Type: application/json

{ "email": "planinic.ivki@gmail.com", "password": "Ivimir11" }

###


POST https://ivoplaninic.net:8881/api/get_user_data
Content-Type: application/json

{
  "token": "2a076df0bfeeaafaf2c7670e50a4d7c7f2a56067"
}

###


POST http://localhost:8881/api/register
Content-Type: application/json

{
  "username": "ivo1",
  "email": "planinic.ivki.fake@gmail.com",
  "password": "Ivimir11"
}

###


POST http://localhost:8881/api/submit_score
Content-Type: application/json

{
  "token": "2e80dbe7225cd2da5219f358942015e707b182a6",
  "time": "1"
}

###


POST https://ivoplaninic.net:8881/api/submit_score
Content-Type: application/json

{
  "token": "2a076df0bfeeaafaf2c7670e50a4d7c7f2a56067",
  "time": "1"
}

###


POST https://ivoplaninic.net:8881/api/get_leaderboard
Content-Type: application/json

{
  "token": "2a076df0bfeeaafaf2c7670e50a4d7c7f2a56067"
}