export const SignsMeaningAndImage: Record<string, string> = {
    "Opasnost na cesti":require("./znakoviSlike/A01_opasnost_tn.png"),
    "Raskrižje cesta iste važnosti":require("./znakoviSlike/A02_raskrizje_tn.png"),
    "Raskrižje sa sporednom cestom pod pravim kutom":require("./znakoviSlike/A03_raskrizje_tn.png"),
    "Spajanje sporedne ceste sa lijeve strane pod pravim kutom":require("./znakoviSlike/A04_raskrizje_tn.png"),
    "Spajanje sporedne ceste pod pravim kutom s desne strane":require("./znakoviSlike/A05_raskrizje_tn.png"),
    "Spajanje sporedne ceste pod oštrim kutom s lijeve strane":require("./znakoviSlike/A06_raskrizje_tn.png"),
    "Spajanje sporedne ceste pod oštrim kutom s desne strane":require("./znakoviSlike/A07_raskrizje_tn.png"),
}


const _SignsMeaningAndImage: Record<string, string> = {
    "A01_opasnost_tn.png":"Opasnost na cesti",
    "A02_raskrizje_tn.png":"Raskrižje cesta iste važnosti",
    "A03_raskrizje_tn.png":"Raskrižje sa sporednom cestom pod pravim kutom",
    "A04_raskrizje_tn.png":"Spajanje sporedne ceste sa lijeve strane pod pravim kutom",
    "A05_raskrizje_tn.png":"Spajanje sporedne ceste pod pravim kutom s desne strane",
    "A06_raskrizje_tn.png":"Spajanje sporedne ceste pod oštrim kutom s lijeve strane",
    "A07_raskrizje_tn.png":"Spajanje sporedne ceste pod oštrim kutom s desne strane",
    "A08_zavoj_tn.png":"Zavoj ulijevo",
    "A09_zavoj_tn.png":"Zavoj udesno",
    "A10_zavoj_tn.png":"Dvostruki zavoj ili više uzastopnih zavoja od kojih je prvi ulijevo",
    "A11_zavoj_tn.png":"Dvostruki zavoj ili više uzastopnih zavoja od kojih je prvi udesno",
    "A12_nizbrdica_tn.png":"Opasna nizbrdica",
    "A13_uzbrdica_tn.png":"Opasna uzbrdica",
    "A14_suzenje_tn.png":"Suženje ceste",
    "A15_suzenje_tn.png":"Suženje ceste s desne strane",
    "A16_suzenje_tn.png":"Suženje ceste s lijeve strane",
    "A17_neravnina_tn.png":"Neravan kolnik",
    "A18_neravnina_tn.png":"Neravan kolnik",
    "A19_neravnina_tn.png":"Neravan kolnik",
    "A20_sklizak_tn.png":"Sklizak kolnik",
    "A21_kamenje_tn.png":"Kamenje pršti",
    "A22_odron_tn.png":"Kamenje pada",
    "A23_semafor_tn.png":"Nailazak na prometna svjetla",
    "A24_semafor_tn.png":"Nailazak na prometna svjetla",
    "A25_radovi_tn.png":"Radovi na cesti",
    "A26_obasmjera_tn.png":"Promet u oba smjera",
    "A27_kruznitok_tn.png":"Raskrižje s kružnim tokom prometa",
    "A28_poledica_tn.png":"Poledica",
    "A29_prevrtanje_tn.png":"Prevrtanje ili iskliznuće vozila",
    "A30_kolona_tn.png":"Kolona vozila",
    "A31_bankina_tn.png":"Neutvrđena bankina",
    "A32_pjesaci_tn.png":"Pješaci na cesti",
    "A33_zebra_tn.png":"Obilježen pješački prelaz",
    "A34_djeca_tn.png":"Djeca na cesti",
    "A35_aerodrom_tn.png":"Blizina zrakoplovne ceste",
    "A36_tunel_tn.png":"Tunel",
    "A37_vjetar_tn.png":"Bočni vjetar",
    "A38_pozar_tn.png":"Opasnost od požara",
    "A39_biciklist_tn.png":"Biciklisti na cesti",
    "A40_pokretnimost_tn.png":"Pokretni most",
    "A41_obala_tn.png":"Blizina obale",
    "A42_tramvaj_tn.png":"Tramvajska pruga",
    "A43_domaceziv_tn.png":"Domaće životinje na cesti",
    "A44_divljac_tn.png":"Divljač na cesti",
    "A45_pruga_tn.png":"Prijelaz ceste preko željezničke pruge s branicima ili polubranicima",
    "A46_vlak_tn.png":"Prijelaz ceste preko željezničke pruge bez branika ili polubranika",
    "A47_andrija_tn.png":"Andrijin križ",
    "A48_andrija_tn.png":"Andrijin križ",
    "A49_blizinapruge_tn.png":"Približavanje prijelazu ceste preko željezničke pruge s branicima ili polubranicima",
    "A50_blizinavlaka_tn.png":"Približavanje prijelazu ceste preko željezničke pruge bez branika ili polubranika",
    "B01_prednost_tn.png":"Raskrižje s cestom koja ima prednost prolaza",
    "B02_stop_tn.png":"Obvezno zaustavljanje",
    "B03_obasmjera_tn.png":"Zabrana prometa u oba smjera",
    "B04_jedansmjer_tn.png":"Zabrana prometa u jednom smjeru",
    "B05_motornavoz_tn.png":"Zabrana prometa za sva motorna vozila osim za motocikle bez prikolice i mopede",
    "B06_autobusi_tn.png":"Zabrana prometa za autobuse",
    "B07_kamioni_tn.png":"Zabrana prometa za teretne automobile",
    "B08_cisterne_tn.png":"Zabrana prometa za cisterne",
    "B09_eksploziv_tn.png":"Zabrana prometa za vozila koja prevoze eksploziv ili neke lakozapaljive tvari",
    "B10_opasne_tn.png":"Zabrana prometa za vozila koja prevoze opasne tvari",
    "B11_prikolica_tn.png":"Zabrana prometa za sva motorna vozila koja vuku priključno vozilo",
    "B12_prikolice_tn.png":"Zabrana prometa za teretni automobil koji vuče priključno vozilo",
    "B13_traktor_tn.png":"Zabrana prometa za traktore",
    "B14_motor_tn.png":"Zabrana prometa za motocikle",
    "B15_moped_tn.png":"Zabrana prometa za mopede",
    "B16_bicikl_tn.png":"Zabrana prometa za bicikle",
    "B17_bicmot_tn.png":"Zabrana prometa za mopede i bicikle",
    "B18_zaprega_tn.png":"Zabrana prometa za zaprežna vozila",
    "B19_kolica_tn.png":"Zabrana prometa za ručna kolica",
    "B20_motorna_tn.png":"Zabrana prometa za sva motorna vozila",
    "B21_pjesaci_tn.png":"Zabrana prometa za pješake",
    "B22_sirina_tn.png":"Zabrana prometa za vozila čija ukupna širina prelazi određenu širinu",
    "B23_visina_tn.png":"Zabrana prometa za vozila čija ukupna visina prelazi odeđenu visinu",
    "B24_tezina_tn.png":"Zabrana prometa za vozila čija ukupna masa prelazi određenu masu",
    "B25_osovina_tn.png":"Zabrana prometa za vozila koja prekoračuju određeno osovinsko opterećenje",
    "B26_duzina_tn.png":"Zabrana prometa za vozila koja prekoračuju određenu dužinu",
    "B27_razdaljina_tn.png":"Najmanja udaljenost između vozila",
    "B28_zavoj_tn.png":"Zabrana skretanja ulijevo",
    "B29_zavoj_tn.png":"Zabrana skretanja udesno",
    "B30_polukruzno_tn.png":"Zabrana polukružnog okretanja",
    "B31_brzina_tn.png":"Ograničenje brzine",
    "B32_pretjecanje_tn.png":"Zabrana pretjecanja svih motornih vozila osim motocikla bez prikolice i mopeda",
    "B33_pretjecanje_tn.png":"Zabrana pretjecanja za teretne automobile",
    "B34_carina_tn.png":"Zabrana prolaska bez zaustavljanja - carina",
    "B35_policija_tn.png":"Zabrana prolaska bez zaustavljanja - policija",
    "B36_cestarina_tn.png":"Zabrana prolaska bez zaustavljanja - cestarina",
    "B37_truba_tn.png":"Zabrana davanja zvučnih znakova",
    "B38_prednost_tn.png":"Prednost prolaska za vozila iz suprotnog smjera",
    "B39_parkiranje_tn.png":"Zabrana zaustavljanja i parkiranja",
    "B40_parkiranje_tn.png":"Zabrana parkiranja",
    "B41_parkiranje_tn.png":"Izmjenično parkiranje",
    "B42_parkiranje_tn.png":"Izmjenično parkiranje",
    "B43_fotografiranje_tn.png":"Zabranjeno fotografiranje",
    "B44_brzina_tn.png":"Najmanja dopuštena brzina",
    "B45_zimska_tn.png":"Zimska oprema",
    "B46_bicikl_tn.png":"Biciklistička staza",
    "B47_roditelji_tn.png":"Pješačka staza",
    "B48_pjebic_tn.png":"Pješačka i biciklistička staza",
    "B49_konj_tn.png":"Staza za jahače",
    "B50_smjer_tn.png":"Obvezan smjer",
    "B51_smjer_tn.png":"Obvezan smjer",
    "B52_smjer_tn.png":"Obvezan smjer",
    "B53_smjer_tn.png":"Obvezan smjer",
    "B54_smjer_tn.png":"Obvezan smjer",
    "B55_smjer_tn.png":"Obvezan smjer",
    "B56_smjer_tn.png":"Dopušteni smjerovi",
    "B57_smjer_tn.png":"Dopušteni smjerovi",
    "B58_smjer_tn.png":"Dopušteni smjerovi",
    "B59_smjer_tn.png":"Obvezno obilaženje s desne strane",
    "B60_smjer_tn.png":"Obvezno obilaženje s lijeve strane",
    "B61_smjer_tn.png":">Dopušteno obilaženje",
    "B62_tok_tn.png":"Kružni tok prometa",
    "C001_prednost_tn.png":"Prednost prolaska prema vozilima iz suprotnog smjera",
    "C002_zebra_tn.png":"Obilježen pješački prelaz",
    "C003_staza_tn.png":"Obilježen prijelaz biciklističke staze",
    "C004_djeca_tn.png":"Djeca na cesti",
    "C005_stube_tn.png":"Podzemni ili nadzemni pješački prelaz",
    "C006_smjer_tn.png":"Cesta sa jednosmjernim prometom",
    "C007_smjer_tn.png":"Cesta sa jednosmjernim prometom",
    "C008_prednost_tn.png":"Cesta s prednošću prolaska",
    "C009_zavrsetak_tn.png":"Završetak ceste s prednošću prolaska",
    "C010_izbocina_tn.png":"Izbočina na cesti",
    "C011_prestanak_tn.png":"Prestanak zabrane pretjecanja svih motornih vozila osim mopeda",
    "C012_prestanak_tn.png":"Prestanak zabrane pretjecanja za teretne automobile",
    "C013_prestanak_tn.png":"Prestanak ograničenja brzine",
    "C014_prestanak_tn.png":"Prestanak najmanje dopuštene brzine",
    "C015_prestanak_tn.png":"Prestanak zabrane davanja zvučnih signala",
    "C016_prestanak_tn.png":"Prestanak svih zabrana",
    "C017_prestanak_tn.png":"Prestanak obvezne uporabe zimske opreme",
    "C018_prestanak_tn.png":"Završetak bicikllističke staze",
    "C019_prestanak_tn.png":"Završetak pješačke staze",
    "C020_prestanak_tn.png":"Završetak staze za jahače",
    "C021_zona_tn.png":"Zona u kojoj je ograničena brzina",
    "C022_zona_tn.png":"Završetak zone u kojoj je ograničena brzina",
    "C023_zona_tn.png":"Pješačka zona",
    "C024_zona_tn.png":"Završetak pješačke zone",
    "C025_igraliste_tn.png":"Područje smirenog prometa",
    "C026_prestanak_tn.png":"Završetak područja smirenog prometa",
    "C027_zona_tn.png":"Zona u kojoj je ograničeno trajanje parkiranja",
    "C028_prestanak_tn.png":"Završetak zone u kojoj je ograničeno trajanje parkiranja",
    "C029_brzina_tn.png":"Brzina koja se preporučuje",
    "C030_prestanak_tn.png":"Prestanak preporučene brzine",
    "C031_patrola_tn.png":"Školska patrola",
    "C032_bolnica_tn.png":"Bolnica",
    "C033_pomoc_tn.png":"Ustanova hitne medicinske pomoći",
    "C034_policija_tn.png":"Policijska postaja",
    "C035_parkiraliste_tn.png":"Parkiralište",
    "C036_parkirliste_tn.png":"Garaža",
    "C037_naplata_tn.png":"Vremensko ograničenje parkiranja",
    "C038_telefon_tn.png":"Telefon",
    "C039_benzin_tn.png":"Benziska postaja",
    "C040_info_tn.png":"Informacije",
    "C041_hotel_tn.png":"Hotel ili motel",
    "C042_restoran_tn.png":"Restoran",
    "C043_voda_tn.png":"Pitka voda",
    "C044_bus_tn.png":"Stajalište autobusa",
    "C045_tramvaj_tn.png":"Stajalište tramvaja",
    "C046_taxi_tn.png":"Taxi",
    "C047-avion_tn.png":"Zračna luka",
    "C048_brod_tn.png":"Luka - pristanište - trajekt",
    "C049_trajekt_tn.png":"Luka - pristanište - trajekt",
    "C050_brodic_tn.png":"Marina",
    "C051_kavana_tn.png":"Kavana",
    "C052_otpad_tn.png":"Mjesto za ispuštanje otpadnih voda",
    "C053_kamp_tn.png":"Teren za kampiranje pod šatorima",
    "C054_kamp_tn.png":"Teren za kampiranje u prikolicama",
    "C055_kamp_tn.png":"Teren za kampiranje u vozilima",
    "C056_izletiste_tn.png":"Teren uređen za izletnike",
    "C057_planinarski_tn.png":"Planinarski dom",
    "C058_vatrogasci_tn.png":"Vatrogasni aparat",
    "C059_vuca_tn.png":"Vozilo za pomoć na cesti",
    "C060_radionica_tn.png":"Radionica za popravak vozila",
    "C061_praonica_tn.png":"Praonica vozila",
    "C062_wc_tn.png":"WC",
    "C063_tn.png":"Radionica za popravak guma",
    "C064_radio_tn.png":"Radiopostaja",
    "C065_cisto_tn.png":"Vodozaštitno područje",
    "C066_autocesta_tn.png":"Autocesta",
    "C067_autocesta_tn.png":"Završetak autoceste",
    "C068_brza_cesta_tn.png":"Cesta namijenjena isključivo za promet motornih vozila - brza cesta",
    "C069_brza_cesta_tn.png":"Završetak ceste namijenjene isključivo za promet motornih vozila - brze ceste",
    "C070_smjer_tn.png":"Slijepa cesta",
    "C071_smjer_tn.png":"Smjer kretanja vozila do raskrižja na kojem je zabranjeno skretanje ulijevo",
    "C072_sos_tn.png":"Ugibalište za zaustavljanje vozila u nuždi",
    "C073_ugibaliste_tn.png":"Ugibalište za zaustavljanje",
    "C074_prijevoj_tn.png":"Planinski prijevoj",
    "C075_rijeka_tn.png":"Rijeka",
    "C076_tunel_tn.png":"Cestovna građevina",
    "C077_most_tn.png":"Cestovna građevina",
    "C078_policija_tn.png":"Policijska postaja",
    "C079_toponim_tn.png":"Naziv naseljenog mjesta",
    "C080_prestanak_tn.png":"Završetak naseljenog mjesta",
    "C081_udaljenost_tn.png":"Putokaz",
    "C082_udaljenost_tn.png":"Putokaz",
    "C083_zracna_tn.png":"Putokaz za zračnu luku",
    "C084-putokaz-za-autocestu-tn.png":"Putokaz za autocestu ili brzu cestu",
    "C085-Putokaz-za-autocestu-tn.png":"Putokaz za autocestu ili brzu cestu",
    "C086_raskrizje_tn.png":"Prestrojavanje vozila",
    "C087_raskrizje_tn.png":"Prestrojavanje vozila s nazivima mjesta",
    "C088_bus_tn.png":"Otvaranje prometne trake za vozila javnog prijevoza putnika",
    "C089_bus_tn.png":"Zatvaranje prometne trake za vozila javnog prijevoza putnika",
    "C090_tramvaj_tn.png":"Prometna traka za vozila javnog prijevoza putnika",
    "C091-otvaranje-prometne-trake-tn.png":"Otvaranje prometne trake",
    "C092-zatvaranje-prometne-trake-tn.png":"Zatvaranje prometne trake",
    "C093-dopustena-brzina-na-pojedinoj-prometnoj-traci-tn.png":"Dopuštena brzina na pojedinoj prometnoj traci",
    "C094-prometna-traka-za-spora-vozila-tn.png":"Prometna traka za spora vozila",
    "C095-zatvaranje-prometne-trake-za-spora-vozila-tn.png":"Zatvaranje prometne trake za spora vozila",
    "C096_izlaz_tn.png":"Izlaz s autoceste ili brze ceste",
    "C097-ploca-za-oznacavanje-izlaza-tn.png":"Ploča za označavanje izlaza",
    "C098-odmoriste-tn.png":"Odmorište",
    "C099-Odmoriste-tn.png":"Odmorište",
    "C100-zabrana-ulaska-odredenih-vozila-na-autocestu-tn.png":"Zabrana ulaska određenih vrsta vozila na autocestu",
    "C101-cestarina-tn.png":"Cestarina",
    "C102-obavijest-o-naplati-cestarine-tn.png":"Obavijest o naplati cestarine",
    "C103-obvezno-uzimanje-naplatne-karte-tn.png":"Obvezno uzimanje naplatne karte",
    "C104-naplata-cestarine-tn.png":"Naplata cestarine",
    "C105-elektronska-naplata-cestarine-tn.png":"Elektronska naplata cestarine",
    "C106-naplata-cestarine-smart-karticom-tn.png":"Naplata cestarine smart karticom",
    "C107-predznak-za-obilazak-tn.png":"Predznak za obilazak",
    "C108_obilazak_tn.png":"Putokaz obilaska",
    "C109_flaster_tn.png":"Traka za prekrivanje znakova",
    "C110_obilazak_tn.png":"Obilazan smjer za određene vrste vozila",
    "C111_obilazak_tn.png":"Obilazan smjer za određene vrste vozila",
    "C112_regulacija_tn.png":"Predznak za ručno upravljanje prometom",
    "C113_smjer_tn.png":"Prometne trake namjenjene određenoj vrsti vozila",
    "C114_smjer_tn.png":"Prometne trake namjenjene određenoj vrsti vozila",
    "C115_obilazak_tn.png":"Predznak za preusmjeravanje prometa na cesti s odvojenim kolničkim trakama",
    "C116_obilazak_tn.png":"Predznak za preusmjeravanje prometa na cesti s odvojenim kolničkim trakama",
    "C117_obilazak-tn.png":"Predznak za preusmjeravanje prometa na cesti s odvojenim kolničkim trakama",
    "C118_obilazak-tn.png":"Predznak za preusmjeravanje prometa na cesti s odvojenim kolničkim trakama",
    "C119_obilazak_tn.png":"Predznak za preusmjeravanje prometa na cesti s odvojenim kolničkim trakama",
    "C120_ulica_tn.png":"Ploča za označavanje ulica",
    "C121-republika-hrvatska-tn.png":"Republika Hrvatska",
    "C122-ogranicenje-najvece-dopustene-brzine-u-RH-tn.png":"Ograničenje najveće dopuštene brzine na hrvatskim cestama",
    "C123_zaauto_tn.png":"Nacionalna oznaka",
    "C124-sigurnosni-izlaz-tn.png":"Sigurnosni izlaz",
    "C125-smjer-za-sigurnosni-izlaz-tn.png":"Smjer za sigurnosni izlaz",
    "C126_oznaka_tn.png":"Oznaka broja izlaza iz čvorišta",
    "C127_oznaka_tn.png":"Broj međunarodne ceste",
    "C128_oznaka_tn.png":"Broj autoceste",
    "C129_oznaka_tn.png":"Broj državne ceste",
    "C130_oznaka_tn.png":"Broj županijske ceste",
    "C131-kilometarska-oznaka-tn.png":"Kilometarska oznaka za autoceste ili brze ceste",
    "C132_oznaka_tn.png":"Oznaka dionice državne ceste",
    "C133_oznaka_tn.png":"Oznaka dionice županijske ceste",
    "znak-d01.png":"Predputokaz za izlaz s autoceste ili brze ceste s oznakom izlaza",
    "znak-d02_mali.png":"Predputokaz za čvorište autocesta s oznakom čvorišta",
    "znak-d03_mali.png":"Raskrižje",
    "znak-d04_mali.png":"Raskrižje",
    "znak-d05_mali.png":"Raskrižje kružnog oblika",
    "znak-d06_mali.png":"Predputokazna ploča",
    "znak-d07_mali.png":"Predputokazna ploča",
    "znak-d08_mali.png":"Predputokazna ploča",
    "znak-d09_mali.png":"Predputokaz",
    "znak-d10_mali.png":"Predputokaz za izlaz",
    "znak-d11_mali.png":"Predputokaz za izlaz",
    "znak-d12_mali.png":"Putokazna ploča",
    "znak-d13_mali.png":"Putokaz na portalu iznad jedne prometne trake",
    "znak-d14_mali.png":"Putokaz na portalu iznad jedne prometne trake",
    "znak-d15_mali.png":"Putokaz na portalu iznad dvije prometne trake",
    "znak-d16_mali.png":"Putokaz na portalu iznad dvije prometne trake",
    "znak-d17_mali.png":"Potvrda smjera",
    "e01.png":"Predputokaz za izlaz s autoceste ili brze ceste s oznakom izlaza",
    "e02.png":"Predputokaz za čvorište autocesta s oznakom čvorišta",
    "e03.png":"Raskrižje",
    "e04.png":"Raskrižje",
    "e05.png":"Raskrižje kružnog oblika",
    "e06.png":"Predputokazna ploča",
    "e07.png":"Predputokazna ploča",
    "e08.png":"Predputokazna ploča",
    "e23.png":"Predputokaz",
    "e31.png":"Predputokaz za izlaz",
    "e35.png":"Predputokaz za izlaz",
    "e36.png":"Putokazna ploča",
    "e43.png":"Putokaz na portalu iznad jedne prometne trake",
 }