export const SignsMeaningAndImage: Record<string, string> = {
    "Opasnost na cesti": require("./znakoviSlike/A01_opasnost_tn.jpg"),
    "Raskrižje cesta iste važnosti": require("./znakoviSlike/A02_raskrizje_tn.jpg"),
    "Raskrižje sa sporednom cestom pod pravim kutom": require("./znakoviSlike/A03_raskrizje_tn.jpg"),
    "Spajanje sporedne ceste sa lijeve strane pod pravim kutom": require("./znakoviSlike/A04_raskrizje_tn.jpg"),
    "Spajanje sporedne ceste pod pravim kutom s desne strane": require("./znakoviSlike/A05_raskrizje_tn.jpg"),
    "Spajanje sporedne ceste pod oštrim kutom s lijeve strane": require("./znakoviSlike/A06_raskrizje_tn.jpg"),
    "Spajanje sporedne ceste pod oštrim kutom s desne strane": require("./znakoviSlike/A07_raskrizje_tn.jpg"),
    "Zavoj ulijevo": require("./znakoviSlike/A08_zavoj_tn.jpg"),
    "Zavoj udesno": require("./znakoviSlike/A09_zavoj_tn.jpg"),
    "Dvostruki zavoj ili više uzastopnih zavoja od kojih je prvi ulijevo": require("./znakoviSlike/A10_zavoj_tn.jpg"),
    "Dvostruki zavoj ili više uzastopnih zavoja od kojih je prvi udesno": require("./znakoviSlike/A11_zavoj_tn.jpg"),
    "Opasna nizbrdica": require("./znakoviSlike/A12_nizbrdica_tn.jpg"),
    "Opasna uzbrdica": require("./znakoviSlike/A13_uzbrdica_tn.jpg"),
    "Suženje ceste": require("./znakoviSlike/A14_suzenje_tn.jpg"),
    "Suženje ceste s desne strane": require("./znakoviSlike/A15_suzenje_tn.jpg"),
    "Suženje ceste s lijeve strane": require("./znakoviSlike/A16_suzenje_tn.jpg"),
    "Neravan kolnik": require("./znakoviSlike/A17_neravnina_tn.jpg"),
    "Sklizak kolnik": require("./znakoviSlike/A20_sklizak_tn.jpg"),
    "Kamenje pršti": require("./znakoviSlike/A21_kamenje_tn.jpg"),
    "Kamenje pada": require("./znakoviSlike/A22_odron_tn.jpg"),
    "Nailazak na prometna svjetla": require("./znakoviSlike/A23_semafor_tn.jpg"),
    "Radovi na cesti": require("./znakoviSlike/A25_radovi_tn.jpg"),
    "Promet u oba smjera": require("./znakoviSlike/A26_obasmjera_tn.jpg"),
    "Raskrižje s kružnim tokom prometa": require("./znakoviSlike/A27_kruznitok_tn.jpg"),
    "Poledica": require("./znakoviSlike/A28_poledica_tn.jpg"),
    "Prevrtanje ili iskliznuće vozila": require("./znakoviSlike/A29_prevrtanje_tn.jpg"),
    "Kolona vozila": require("./znakoviSlike/A30_kolona_tn.jpg"),
    "Neutvrđena bankina": require("./znakoviSlike/A31_bankina_tn.jpg"),
    "Pješaci na cesti": require("./znakoviSlike/A32_pjesaci_tn.jpg"),
    "Obilježen pješački prelaz": require("./znakoviSlike/A33_zebra_tn.jpg"),
    "Djeca na cesti": require("./znakoviSlike/A34_djeca_tn.jpg"),
    "Blizina zrakoplovne ceste": require("./znakoviSlike/A35_aerodrom_tn.jpg"),
    "Tunel": require("./znakoviSlike/A36_tunel_tn.jpg"),
    "Bočni vjetar": require("./znakoviSlike/A37_vjetar_tn.jpg"),
    "Opasnost od požara": require("./znakoviSlike/A38_pozar_tn.jpg"),
    "Biciklisti na cesti": require("./znakoviSlike/A39_biciklist_tn.jpg"),
    "Pokretni most": require("./znakoviSlike/A40_pokretnimost_tn.jpg"),
    "Blizina obale": require("./znakoviSlike/A41_obala_tn.jpg"),
    "Tramvajska pruga": require("./znakoviSlike/A42_tramvaj_tn.jpg"),
    "Domaće životinje na cesti": require("./znakoviSlike/A43_domaceziv_tn.jpg"),
    "Divljač na cesti": require("./znakoviSlike/A44_divljac_tn.jpg"),
    "Prijelaz ceste preko željezničke pruge s branicima ili polubranicima": require("./znakoviSlike/A45_pruga_tn.jpg"),
    "Prijelaz ceste preko željezničke pruge bez branika ili polubranika": require("./znakoviSlike/A46_vlak_tn.jpg"),
    "Andrijin križ": require("./znakoviSlike/A47_andrija_tn.jpg"),
    "Približavanje prijelazu ceste preko željezničke pruge s branicima ili polubranicima": require("./znakoviSlike/A49_blizinapruge_tn.jpg"),
    "Približavanje prijelazu ceste preko željezničke pruge bez branika ili polubranika": require("./znakoviSlike/A50_blizinavlaka_tn.jpg"),
    "Raskrižje s cestom koja ima prednost prolaza": require("./znakoviSlike/B01_prednost_tn.jpg"),
    "Obvezno zaustavljanje": require("./znakoviSlike/B02_stop_tn.jpg"),
    "Zabrana prometa u oba smjera": require("./znakoviSlike/B03_obasmjera_tn.jpg"),
    "Zabrana prometa u jednom smjeru": require("./znakoviSlike/B04_jedansmjer_tn.jpg"),
    "Zabrana prometa za sva motorna vozila osim za motocikle bez prikolice i mopede": require("./znakoviSlike/B05_motornavoz_tn.jpg"),
    "Zabrana prometa za autobuse": require("./znakoviSlike/B06_autobusi_tn.jpg"),
    "Zabrana prometa za teretne automobile": require("./znakoviSlike/B07_kamioni_tn.jpg"),
    "Zabrana prometa za cisterne": require("./znakoviSlike/B08_cisterne_tn.jpg"),
    "Zabrana prometa za vozila koja prevoze eksploziv ili neke lakozapaljive tvari": require("./znakoviSlike/B09_eksploziv_tn.jpg"),
    "Zabrana prometa za vozila koja prevoze opasne tvari": require("./znakoviSlike/B10_opasne_tn.jpg"),
    "Zabrana prometa za sva motorna vozila koja vuku priključno vozilo": require("./znakoviSlike/B11_prikolica_tn.jpg"),
    "Zabrana prometa za teretni automobil koji vuče priključno vozilo": require("./znakoviSlike/B12_prikolice_tn.jpg"),
    "Zabrana prometa za traktore": require("./znakoviSlike/B13_traktor_tn.jpg"),
    "Zabrana prometa za motocikle": require("./znakoviSlike/B14_motor_tn.jpg"),
    "Zabrana prometa za mopede": require("./znakoviSlike/B15_moped_tn.jpg"),
    "Zabrana prometa za bicikle": require("./znakoviSlike/B16_bicikl_tn.jpg"),
    "Zabrana prometa za mopede i bicikle": require("./znakoviSlike/B17_bicmot_tn.jpg"),
    "Zabrana prometa za zaprežna vozila": require("./znakoviSlike/B18_zaprega_tn.jpg"),
    "Zabrana prometa za ručna kolica": require("./znakoviSlike/B19_kolica_tn.jpg"),
    "Zabrana prometa za sva motorna vozila": require("./znakoviSlike/B20_motorna_tn.jpg"),
    "Zabrana prometa za pješake": require("./znakoviSlike/B21_pjesaci_tn.jpg"),
    "Zabrana prometa za vozila čija ukupna širina prelazi određenu širinu": require("./znakoviSlike/B22_sirina_tn.jpg"),
    "Zabrana prometa za vozila čija ukupna visina prelazi odeđenu visinu": require("./znakoviSlike/B23_visina_tn.jpg"),
    "Zabrana prometa za vozila čija ukupna masa prelazi određenu masu": require("./znakoviSlike/B24_tezina_tn.jpg"),
    "Zabrana prometa za vozila koja prekoračuju određeno osovinsko opterećenje": require("./znakoviSlike/B25_osovina_tn.jpg"),
    "Zabrana prometa za vozila koja prekoračuju određenu dužinu": require("./znakoviSlike/B26_duzina_tn.jpg"),
    "Najmanja udaljenost između vozila": require("./znakoviSlike/B27_razdaljina_tn.jpg"),
    "Zabrana skretanja ulijevo": require("./znakoviSlike/B28_zavoj_tn.jpg"),
    "Zabrana skretanja udesno": require("./znakoviSlike/B29_zavoj_tn.jpg"),
    "Zabrana polukružnog okretanja": require("./znakoviSlike/B30_polukruzno_tn.jpg"),
    "Ograničenje brzine": require("./znakoviSlike/B31_brzina_tn.jpg"),
    "Zabrana pretjecanja svih motornih vozila osim motocikla bez prikolice i mopeda": require("./znakoviSlike/B32_pretjecanje_tn.jpg"),
    "Zabrana pretjecanja za teretne automobile": require("./znakoviSlike/B33_pretjecanje_tn.jpg"),
    "Zabrana prolaska bez zaustavljanja - carina": require("./znakoviSlike/B34_carina_tn.jpg"),
    "Zabrana prolaska bez zaustavljanja - policija": require("./znakoviSlike/B35_policija_tn.jpg"),
    "Zabrana prolaska bez zaustavljanja - cestarina": require("./znakoviSlike/B36_cestarina_tn.jpg"),
    "Zabrana davanja zvučnih znakova": require("./znakoviSlike/B37_truba_tn.jpg"),
    "Prednost prolaska za vozila iz suprotnog smjera": require("./znakoviSlike/B38_prednost_tn.jpg"),
    "Zabrana zaustavljanja i parkiranja": require("./znakoviSlike/B39_parkiranje_tn.jpg"),
    "Zabrana parkiranja": require("./znakoviSlike/B40_parkiranje_tn.jpg"),
    "Izmjenično parkiranje": require("./znakoviSlike/B41_parkiranje_tn.jpg"),
    "Zabranjeno fotografiranje": require("./znakoviSlike/B43_fotografiranje_tn.jpg"),
    "Najmanja dopuštena brzina": require("./znakoviSlike/B44_brzina_tn.jpg"),
    "Zimska oprema": require("./znakoviSlike/B45_zimska_tn.jpg"),
    "Biciklistička staza": require("./znakoviSlike/B46_bicikl_tn.jpg"),
    "Pješačka staza": require("./znakoviSlike/B47_roditelji_tn.jpg"),
    "Pješačka i biciklistička staza": require("./znakoviSlike/B48_pjebic_tn.jpg"),
    "Staza za jahače": require("./znakoviSlike/B49_konj_tn.jpg"),
    "Obvezan smjer": require("./znakoviSlike/B50_smjer_tn.jpg"),
    "Dopušteni smjerovi": require("./znakoviSlike/B56_smjer_tn.jpg"),
    "Obvezno obilaženje s desne strane": require("./znakoviSlike/B59_smjer_tn.jpg"),
    "Obvezno obilaženje s lijeve strane": require("./znakoviSlike/B60_smjer_tn.jpg"),
    ">Dopušteno obilaženje": require("./znakoviSlike/B61_smjer_tn.jpg"),
    "Kružni tok prometa": require("./znakoviSlike/B62_tok_tn.jpg"),
    "Prednost prolaska prema vozilima iz suprotnog smjera": require("./znakoviSlike/C001_prednost_tn.jpg"),
    "Obilježen prijelaz biciklističke staze": require("./znakoviSlike/C003_staza_tn.jpg"),
    "Podzemni ili nadzemni pješački prelaz": require("./znakoviSlike/C005_stube_tn.jpg"),
    "Cesta sa jednosmjernim prometom": require("./znakoviSlike/C006_smjer_tn.jpg"),
    "Cesta s prednošću prolaska": require("./znakoviSlike/C008_prednost_tn.jpg"),
    "Završetak ceste s prednošću prolaska": require("./znakoviSlike/C009_zavrsetak_tn.jpg"),
    "Izbočina na cesti": require("./znakoviSlike/C010_izbocina_tn.jpg"),
    "Prestanak zabrane pretjecanja svih motornih vozila osim mopeda": require("./znakoviSlike/C011_prestanak_tn.jpg"),
    "Prestanak zabrane pretjecanja za teretne automobile": require("./znakoviSlike/C012_prestanak_tn.jpg"),
    "Prestanak ograničenja brzine": require("./znakoviSlike/C013_prestanak_tn.jpg"),
    "Prestanak najmanje dopuštene brzine": require("./znakoviSlike/C014_prestanak_tn.jpg"),
    "Prestanak zabrane davanja zvučnih signala": require("./znakoviSlike/C015_prestanak_tn.jpg"),
    "Prestanak svih zabrana": require("./znakoviSlike/C016_prestanak_tn.jpg"),
    "Prestanak obvezne uporabe zimske opreme": require("./znakoviSlike/C017_prestanak_tn.jpg"),
    "Završetak bicikllističke staze": require("./znakoviSlike/C018_prestanak_tn.jpg"),
    "Završetak pješačke staze": require("./znakoviSlike/C019_prestanak_tn.jpg"),
    "Završetak staze za jahače": require("./znakoviSlike/C020_prestanak_tn.jpg"),
    "Zona u kojoj je ograničena brzina": require("./znakoviSlike/C021_zona_tn.jpg"),
    "Završetak zone u kojoj je ograničena brzina": require("./znakoviSlike/C022_zona_tn.jpg"),
    "Pješačka zona": require("./znakoviSlike/C023_zona_tn.jpg"),
    "Završetak pješačke zone": require("./znakoviSlike/C024_zona_tn.jpg"),
    "Područje smirenog prometa": require("./znakoviSlike/C025_igraliste_tn.jpg"),
    "Završetak područja smirenog prometa": require("./znakoviSlike/C026_prestanak_tn.jpg"),
    "Zona u kojoj je ograničeno trajanje parkiranja": require("./znakoviSlike/C027_zona_tn.jpg"),
    "Završetak zone u kojoj je ograničeno trajanje parkiranja": require("./znakoviSlike/C028_prestanak_tn.jpg"),
    "Brzina koja se preporučuje": require("./znakoviSlike/C029_brzina_tn.jpg"),
    "Prestanak preporučene brzine": require("./znakoviSlike/C030_prestanak_tn.jpg"),
    "Školska patrola": require("./znakoviSlike/C031_patrola_tn.jpg"),
    "Bolnica": require("./znakoviSlike/C032_bolnica_tn.jpg"),
    "Policijska postaja": require("./znakoviSlike/C034_policija_tn.jpg"),
    "Garaža": require("./znakoviSlike/C036_parkirliste_tn.jpg"),
    "Vremensko ograničenje parkiranja": require("./znakoviSlike/C037_naplata_tn.jpg"),
    "Telefon": require("./znakoviSlike/C038_telefon_tn.jpg"),
    "Benziska postaja": require("./znakoviSlike/C039_benzin_tn.jpg"),
    "Informacije": require("./znakoviSlike/C040_info_tn.jpg"),
    "Hotel ili motel": require("./znakoviSlike/C041_hotel_tn.jpg"),
    "Restoran": require("./znakoviSlike/C042_restoran_tn.jpg"),
    "Pitka voda": require("./znakoviSlike/C043_voda_tn.jpg"),
    "Stajalište autobusa": require("./znakoviSlike/C044_bus_tn.jpg"),
    "Stajalište tramvaja": require("./znakoviSlike/C045_tramvaj_tn.jpg"),
    "Taxi": require("./znakoviSlike/C046_taxi_tn.jpg"),
    "Zračna luka": require("./znakoviSlike/C047-avion_tn.jpg"),
    "Luka - pristanište - trajekt": require("./znakoviSlike/C048_brod_tn.jpg"),
    "Marina": require("./znakoviSlike/C050_brodic_tn.jpg"),
    "Kavana": require("./znakoviSlike/C051_kavana_tn.jpg"),
    "Mjesto za ispuštanje otpadnih voda": require("./znakoviSlike/C052_otpad_tn.jpg"),
    "Teren za kampiranje pod šatorima": require("./znakoviSlike/C053_kamp_tn.jpg"),
    "Teren za kampiranje u prikolicama": require("./znakoviSlike/C054_kamp_tn.jpg"),
    "Teren za kampiranje u vozilima": require("./znakoviSlike/C055_kamp_tn.jpg"),
    "Teren uređen za izletnike": require("./znakoviSlike/C056_izletiste_tn.jpg"),
    "Planinarski dom": require("./znakoviSlike/C057_planinarski_tn.jpg"),
    "Vatrogasni aparat": require("./znakoviSlike/C058_vatrogasci_tn.jpg"),
    "Vozilo za pomoć na cesti": require("./znakoviSlike/C059_vuca_tn.jpg"),
    "Radionica za popravak vozila": require("./znakoviSlike/C060_radionica_tn.jpg"),
    "Praonica vozila": require("./znakoviSlike/C061_praonica_tn.jpg"),
    "WC": require("./znakoviSlike/C062_wc_tn.jpg"),
    "Radionica za popravak guma": require("./znakoviSlike/C063_tn.jpg"),
    "Radiopostaja": require("./znakoviSlike/C064_radio_tn.jpg"),
    "Vodozaštitno područje": require("./znakoviSlike/C065_cisto_tn.jpg"),
    "Autocesta": require("./znakoviSlike/C066_autocesta_tn.jpg"),
    "Završetak autoceste": require("./znakoviSlike/C067_autocesta_tn.jpg"),
    "Cesta namijenjena isključivo za promet motornih vozila - brza cesta": require("./znakoviSlike/C068_brza_cesta_tn.jpg"),
    "Završetak ceste namijenjene isključivo za promet motornih vozila - brze ceste": require("./znakoviSlike/C069_brza_cesta_tn.jpg"),
    "Slijepa cesta": require("./znakoviSlike/C070_smjer_tn.jpg"),
    "Smjer kretanja vozila do raskrižja na kojem je zabranjeno skretanje ulijevo": require("./znakoviSlike/C071_smjer_tn.jpg"),
    "Ugibalište za zaustavljanje vozila u nuždi": require("./znakoviSlike/C072_sos_tn.jpg"),
    "Ugibalište za zaustavljanje": require("./znakoviSlike/C073_ugibaliste_tn.jpg"),
    "Planinski prijevoj": require("./znakoviSlike/C074_prijevoj_tn.jpg"),
    "Rijeka": require("./znakoviSlike/C075_rijeka_tn.jpg"),
    "Cestovna građevina": require("./znakoviSlike/C076_tunel_tn.jpg"),
    "Naziv naseljenog mjesta": require("./znakoviSlike/C079_toponim_tn.jpg"),
    "Završetak naseljenog mjesta": require("./znakoviSlike/C080_prestanak_tn.jpg"),
    "Putokaz za autocestu ili brzu cestu": require("./znakoviSlike/C084-putokaz-za-autocestu-tn.jpg"),
    "Prestrojavanje vozila": require("./znakoviSlike/C086_raskrizje_tn.jpg"),
    "Prestrojavanje vozila s nazivima mjesta": require("./znakoviSlike/C087_raskrizje_tn.jpg"),
    "Otvaranje prometne trake za vozila javnog prijevoza putnika": require("./znakoviSlike/C088_bus_tn.jpg"),
    "Zatvaranje prometne trake za vozila javnog prijevoza putnika": require("./znakoviSlike/C089_bus_tn.jpg"),
    "Prometna traka za vozila javnog prijevoza putnika": require("./znakoviSlike/C090_tramvaj_tn.jpg"),
    "Otvaranje prometne trake": require("./znakoviSlike/C091-otvaranje-prometne-trake-tn.jpg"),
    "Zatvaranje prometne trake": require("./znakoviSlike/C092-zatvaranje-prometne-trake-tn.jpg"),
    "Dopuštena brzina na pojedinoj prometnoj traci": require("./znakoviSlike/C093-dopustena-brzina-na-pojedinoj-prometnoj-traci-tn.jpg"),
    "Prometna traka za spora vozila": require("./znakoviSlike/C094-prometna-traka-za-spora-vozila-tn.jpg"),
    "Zatvaranje prometne trake za spora vozila": require("./znakoviSlike/C095-zatvaranje-prometne-trake-za-spora-vozila-tn.jpg"),
    "Izlaz s autoceste ili brze ceste": require("./znakoviSlike/C096_izlaz_tn.jpg"),
    "Ploča za označavanje izlaza": require("./znakoviSlike/C097-ploca-za-oznacavanje-izlaza-tn.jpg"),
    "Odmorište": require("./znakoviSlike/C098-odmoriste-tn.jpg"),
    "Zabrana ulaska određenih vrsta vozila na autocestu": require("./znakoviSlike/C100-zabrana-ulaska-odredenih-vozila-na-autocestu-tn.jpg"),
    "Cestarina": require("./znakoviSlike/C101-cestarina-tn.jpg"),
    "Obavijest o naplati cestarine": require("./znakoviSlike/C102-obavijest-o-naplati-cestarine-tn.jpg"),
    "Obvezno uzimanje naplatne karte": require("./znakoviSlike/C103-obvezno-uzimanje-naplatne-karte-tn.jpg"),
    "Naplata cestarine": require("./znakoviSlike/C104-naplata-cestarine-tn.jpg"),
    "Elektronska naplata cestarine": require("./znakoviSlike/C105-elektronska-naplata-cestarine-tn.jpg"),
    "Naplata cestarine smart karticom": require("./znakoviSlike/C106-naplata-cestarine-smart-karticom-tn.jpg"),
    "Predznak za obilazak": require("./znakoviSlike/C107-predznak-za-obilazak-tn.jpg"),
    "Putokaz obilaska": require("./znakoviSlike/C108_obilazak_tn.jpg"),
    "Obilazan smjer za određene vrste vozila": require("./znakoviSlike/C110_obilazak_tn.jpg"),
    "Prometne trake namjenjene određenoj vrsti vozila": require("./znakoviSlike/C113_smjer_tn.jpg"),
    "Predznak za preusmjeravanje prometa na cesti s odvojenim kolničkim trakama": require("./znakoviSlike/C117_obilazak-tn.jpg"),
    "Republika Hrvatska": require("./znakoviSlike/C121-republika-hrvatska-tn.jpg"),
    "Ograničenje najveće dopuštene brzine na hrvatskim cestama": require("./znakoviSlike/C122-ogranicenje-najvece-dopustene-brzine-u-RH-tn.jpg"),
    "Sigurnosni izlaz": require("./znakoviSlike/C124-sigurnosni-izlaz-tn.jpg"),
    "Smjer za sigurnosni izlaz": require("./znakoviSlike/C125-smjer-za-sigurnosni-izlaz-tn.jpg"),
    "Oznaka broja izlaza iz čvorišta": require("./znakoviSlike/C126_oznaka_tn.jpg"),
    "Broj međunarodne ceste": require("./znakoviSlike/C127_oznaka_tn.jpg"),
    "Broj autoceste": require("./znakoviSlike/C128_oznaka_tn.jpg"),
    "Broj županijske ceste": require("./znakoviSlike/C130_oznaka_tn.jpg"),
    "Kilometarska oznaka za autoceste ili brze ceste": require("./znakoviSlike/C131-kilometarska-oznaka-tn.jpg"),
    "Oznaka dionice državne ceste": require("./znakoviSlike/C132_oznaka_tn.jpg"),
    "Oznaka dionice županijske ceste": require("./znakoviSlike/C133_oznaka_tn.jpg"),
    "Predputokaz za izlaz s autoceste ili brze ceste s oznakom izlaza": require("./znakoviSlike/znak-d01.jpg"),
    "Predputokaz za čvorište autocesta s oznakom čvorišta": require("./znakoviSlike/znak-d02_mali.jpg"),
    "Raskrižje": require("./znakoviSlike/znak-d03_mali.jpg"),
    "Raskrižje kružnog oblika": require("./znakoviSlike/znak-d05_mali.jpg"),
    "Predputokazna ploča": require("./znakoviSlike/znak-d06_mali.jpg"),
    "Predputokaz": require("./znakoviSlike/znak-d09_mali.jpg"),
    "Predputokaz za izlaz": require("./znakoviSlike/znak-d11_mali.jpg"),
    "Putokazna ploča": require("./znakoviSlike/znak-d12_mali.jpg"),
    "Putokaz na portalu iznad jedne prometne trake": require("./znakoviSlike/znak-d13_mali.jpg"),
    "Putokaz na portalu iznad dvije prometne trake": require("./znakoviSlike/znak-d15_mali.jpg"),
    "Potvrda smjera": require("./znakoviSlike/znak-d17_mali.jpg"),
}
